export const getMockHotels = () => [
  {
    id: 1,
    name: "The Grand Aurum Palace",
    location: "Dhaka, Bangladesh",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=75",
    stars: 5,
    guestRating: 9.4,
    ratingLabel: "Exceptional",
    reviewCount: 2847,
    price: 320,
    originalPrice: 420,
    roomType: "Deluxe Suite",
    breakfast: true,
    freeCancellation: true,
    amenities: ["wifi", "pool", "spa", "gym", "parking", "restaurant"],
    tag: "Best Seller",
    tagColor: "#2C4A6E",
    popular: true,
    newest: false,
  },
  {
    id: 2,
    name: "Skyline Boutique Hotel",
    location: "Dhaka, Bangladesh",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=75",
    stars: 4,
    guestRating: 8.7,
    ratingLabel: "Excellent",
    reviewCount: 1423,
    price: 195,
    originalPrice: 240,
    roomType: "Standard Room",
    breakfast: false,
    freeCancellation: true,
    amenities: ["wifi", "gym", "parking"],
    tag: "Free Cancellation",
    tagColor: "#059669",
    popular: true,
    newest: false,
  },
  {
    id: 3,
    name: "Azure Sea Resort & Spa",
    location: "Dhaka, Bangladesh",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=75",
    stars: 5,
    guestRating: 9.1,
    ratingLabel: "Exceptional",
    reviewCount: 3102,
    price: 450,
    originalPrice: 550,
    roomType: "Family Suite",
    breakfast: true,
    freeCancellation: false,
    amenities: ["wifi", "pool", "spa", "restaurant", "gym"],
    tag: "Spa Included",
    tagColor: "#7c3aed",
    popular: true,
    newest: false,
  },
  {
    id: 4,
    name: "Metropolitan Business Inn",
    location: "Dhaka, Bangladesh",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=75",
    stars: 3,
    guestRating: 7.8,
    ratingLabel: "Good",
    reviewCount: 892,
    price: 95,
    originalPrice: 120,
    roomType: "Standard Room",
    breakfast: true,
    freeCancellation: true,
    amenities: ["wifi", "parking"],
    tag: "Budget Pick",
    tagColor: "#0369a1",
    popular: false,
    newest: false,
  },
  {
    id: 5,
    name: "The Diplomat Residence",
    location: "Dhaka, Bangladesh",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=75",
    stars: 5,
    guestRating: 9.6,
    ratingLabel: "Exceptional",
    reviewCount: 4201,
    price: 680,
    originalPrice: 800,
    roomType: "Presidential Suite",
    breakfast: true,
    freeCancellation: true,
    amenities: ["wifi", "pool", "spa", "gym", "restaurant", "parking"],
    tag: "Top Rated",
    tagColor: "#b45309",
    popular: true,
    newest: true,
  },
  {
    id: 6,
    name: "Garden View Suites",
    location: "Dhaka, Bangladesh",
    image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=75",
    stars: 4,
    guestRating: 8.2,
    ratingLabel: "Very Good",
    reviewCount: 1105,
    price: 155,
    originalPrice: 190,
    roomType: "Deluxe Suite",
    breakfast: true,
    freeCancellation: true,
    amenities: ["wifi", "pool", "parking", "restaurant"],
    tag: null,
    tagColor: null,
    popular: false,
    newest: true,
  },
  {
    id: 7,
    name: "Harbour Lights Hotel",
    location: "Dhaka, Bangladesh",
    image: "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=800&q=75",
    stars: 4,
    guestRating: 8.5,
    ratingLabel: "Excellent",
    reviewCount: 978,
    price: 210,
    originalPrice: 260,
    roomType: "Standard Room",
    breakfast: false,
    freeCancellation: false,
    amenities: ["wifi", "gym", "restaurant"],
    tag: null,
    tagColor: null,
    popular: false,
    newest: true,
  },
  {
    id: 8,
    name: "Prestige Penthouse Hotel",
    location: "Dhaka, Bangladesh",
    image: "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?auto=format&fit=crop&w=800&q=75",
    stars: 5,
    guestRating: 9.3,
    ratingLabel: "Exceptional",
    reviewCount: 2210,
    price: 520,
    originalPrice: 650,
    roomType: "Family Suite",
    breakfast: true,
    freeCancellation: true,
    amenities: ["wifi", "pool", "spa", "gym", "restaurant", "parking"],
    tag: "Family Pick",
    tagColor: "#059669",
    popular: true,
    newest: true,
  },
];