// AIResponses.js
// Local hotel dataset + canned response copy for the AI Concierge.
// No external API calls — everything here is static, local data.

export const HOTELS = [
  {
    id: "h1",
    name: "The Regal Meridian",
    roomType: "Family Suite",
    pricePerNight: 340,
    guestRating: 4.9,
    location: "Downtown Waterfront",
    amenities: ["pool", "gym", "spa", "parking", "breakfast"],
    breakfast: true,
    freeCancellation: true,
    freeParking: true,
    goodForCouples: false,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&q=80",
  },
  {
    id: "h2",
    name: "Aurelia Grand Hotel",
    roomType: "Deluxe King",
    pricePerNight: 210,
    guestRating: 4.7,
    location: "City Centre",
    amenities: ["pool", "spa", "breakfast"],
    breakfast: true,
    freeCancellation: true,
    freeParking: false,
    goodForCouples: true,
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400&q=80",
  },
  {
    id: "h3",
    name: "Havenwood Boutique Inn",
    roomType: "Cozy Double",
    pricePerNight: 89,
    guestRating: 4.2,
    location: "Old Town",
    amenities: ["breakfast"],
    breakfast: true,
    freeCancellation: false,
    freeParking: false,
    goodForCouples: true,
    image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=400&q=80",
  },
  {
    id: "h4",
    name: "Pinehill Family Resort",
    roomType: "Family Suite",
    pricePerNight: 265,
    guestRating: 4.6,
    location: "Lakeside",
    amenities: ["pool", "gym", "parking", "breakfast"],
    breakfast: true,
    freeCancellation: true,
    freeParking: true,
    goodForCouples: false,
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=400&q=80",
  },
  {
    id: "h5",
    name: "Solace Skyline Suites",
    roomType: "Executive Suite",
    pricePerNight: 410,
    guestRating: 4.8,
    location: "Financial District",
    amenities: ["gym", "spa", "parking"],
    breakfast: false,
    freeCancellation: true,
    freeParking: true,
    goodForCouples: true,
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&q=80",
  },
  {
    id: "h6",
    name: "Coral Bay Budget Stay",
    roomType: "Standard Room",
    pricePerNight: 62,
    guestRating: 3.9,
    location: "Airport Road",
    amenities: ["parking"],
    breakfast: false,
    freeCancellation: false,
    freeParking: true,
    goodForCouples: false,
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=400&q=80",
  },
  {
    id: "h7",
    name: "Velora Romance Retreat",
    roomType: "Honeymoon Suite",
    pricePerNight: 298,
    guestRating: 4.9,
    location: "Hillside Vineyard",
    amenities: ["pool", "spa", "breakfast"],
    breakfast: true,
    freeCancellation: true,
    freeParking: false,
    goodForCouples: true,
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400&q=80",
  },
];

export const WELCOME_MESSAGE =
  "👋 Welcome to our Hotel!\nI'm your AI Concierge.\nI can help you find rooms, compare hotels, explain facilities, recommend rooms, answer booking questions and guide you through your reservation.";

export const QUICK_QUESTIONS = [
  { label: "🏨 Recommend a luxury room", query: "Recommend a luxury room" },
  { label: "💰 Cheapest hotel", query: "I need a cheap hotel" },
  { label: "⭐ Best rated hotel", query: "Best hotel" },
  { label: "🏊 Hotels with swimming pool", query: "Pool" },
  { label: "🍽 Hotels with breakfast", query: "Breakfast included" },
  { label: "👨‍👩‍👧 Family room", query: "I need a family room" },
  { label: "🚗 Free parking", query: "Free parking" },
  { label: "💪 Hotels with gym", query: "Gym" },
  { label: "❌ Free cancellation", query: "Free cancellation" },
  { label: "🏖 Best for couples", query: "Best for couples" },
];

export const FALLBACK_RESPONSE =
  "I couldn't find an exact match for that, but I'm happy to help you explore rooms, prices, ratings, or amenities. Try one of the quick questions below, or ask me something like \"family room\" or \"cheapest hotel\".";