// ─────────────────────────────────────────────────────────────────────────
// MASTER ROOM DATA SOURCE
// This is the single source of truth for room objects across the app:
// Rooms page, Hotel Details, Room Details, Booking Page, Offers Page,
// Search Results, and (later) the backend API all read from this file.
// Do not redefine or duplicate room objects anywhere else — import from
// here and derive/filter as needed.
// ─────────────────────────────────────────────────────────────────────────

const AMENITY_ICON = {
  "Free WiFi": "Wifi",
  "Air Conditioning": "Wind",
  "Smart TV": "Tv",
  "Mini Bar": "Wine",
  "Coffee Machine": "Coffee",
  Balcony: "DoorOpen",
  "City View": "Building2",
  "Ocean View": "Waves",
  "Mountain View": "Mountain",
  "Work Desk": "Laptop",
  Bathtub: "Bath",
  "Rain Shower": "ShowerHead",
  "Hair Dryer": "Wind",
  "Safe Box": "Lock",
  Wardrobe: "Shirt",
  Iron: "Iron",
  "Room Service": "BellRing",
  Laundry: "WashingMachine",
  "Breakfast Included": "Coffee",
  Parking: "ParkingCircle",
};

// Amenity label -> icon key lookup, exported so RoomCard (or any future
// component) doesn't have to hardcode this mapping itself.
export const amenityIconMap = AMENITY_ICON;

let autoId = 0;

function createRoom(overrides) {
  autoId += 1;
  const base = {
    id: autoId,
    hotelId: 1,
    hotelName: "The Regal Meridian",
    roomName: "Standard Room",
    roomType: "Standard Room",
    slug: "standard-room",
    description:
      "A thoughtfully appointed room blending modern comfort with classic hospitality.",
    shortDescription: "Comfortable and elegant, perfect for a relaxing stay.",
    price: 149,
    discountPrice: null,
    currency: "USD",
    rating: 4.3,
    reviewCount: 100,
    availability: true,
    featured: false,
    roomNumber: "101",
    capacity: 2,
    adults: 2,
    children: 0,
    bedType: "1 Queen Bed",
    bedCount: 1,
    roomSize: "28 m²",
    floor: 1,
    view: "City View",
    checkIn: "14:00",
    checkOut: "12:00",
    mainImage:
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200",
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1200",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200",
    ],
    panoramaImage: null,
    amenities: ["Free WiFi", "Air Conditioning", "Smart TV", "Room Service"],
    features: ["Non-smoking", "Sound-insulated windows"],
    policies: {
      houseRules: "No smoking. No pets. Quiet hours after 10 PM.",
      maxOccupancy: 2,
    },
    cancellationPolicy: "Free cancellation up to 48 hours before check-in.",
    breakfastIncluded: false,
    parkingIncluded: false,
    wifiIncluded: true,
    petsAllowed: false,
    smoking: false,
    airConditioning: true,
    balcony: false,
    bathroomType: "Ensuite Shower",
    createdAt: "2026-01-10T09:00:00.000Z",
    updatedAt: "2026-06-01T09:00:00.000Z",
    // Extra fields kept for existing search/filter functionality
    location: "Dhaka",
    city: "Dhaka",
    country: "Bangladesh",
  };

  return { ...base, ...overrides };
}

export const roomsData = [
  createRoom({
    hotelId: 5,
    hotelName: "Ivory Tower Business Hotel",
    roomName: "Classic Standard Room",
    roomType: "Standard Room",
    slug: "classic-standard-room",
    description:
      "A well-appointed room with elegant interiors, premium bedding, city views, complimentary WiFi, and modern amenities for a relaxing stay.",
    shortDescription: "Elegant city-view room with premium bedding.",
    price: 149,
    discountPrice: null,
    rating: 4.3,
    reviewCount: 128,
    availability: true,
    featured: true,
    roomNumber: "204",
    capacity: 2,
    adults: 2,
    children: 0,
    bedType: "1 Queen Bed",
    bedCount: 1,
    roomSize: "32 m²",
    floor: 2,
    view: "City View",
    mainImage:
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200",
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1200",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200",
    ],
    panoramaImage:
      "https://pannellum.org/images/alma.jpg",
    amenities: ["Free WiFi", "Air Conditioning", "Smart TV", "Work Desk", "Safe Box"],
    features: ["Non-smoking", "Sound-insulated windows", "Work-friendly desk"],
    cancellationPolicy: "Free cancellation up to 48 hours before check-in.",
    breakfastIncluded: false,
    parkingIncluded: true,
    wifiIncluded: true,
    location: "Dhaka",
    city: "Dhaka",
    country: "Bangladesh",
  }),

  createRoom({
    hotelId: 1,
    hotelName: "The Regal Meridian",
    roomName: "Deluxe Garden View",
    roomType: "Deluxe Room",
    slug: "deluxe-garden-view",
    description:
      "A beautifully designed deluxe room overlooking lush gardens, featuring a king-size bed, marble bathroom, luxury furnishings, and a private balcony.",
    shortDescription: "King-size deluxe room with garden views and balcony.",
    price: 229,
    discountPrice: 199,
    rating: 4.6,
    reviewCount: 94,
    availability: true,
    featured: true,
    roomNumber: "312",
    capacity: 2,
    adults: 2,
    children: 1,
    bedType: "1 King Bed",
    bedCount: 1,
    roomSize: "38 m²",
    floor: 3,
    view: "Garden View",
    mainImage:
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=1200",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200",
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=1200",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200",
    ],
    panoramaImage:
      "https://pannellum.org/images/alma.jpg",
    amenities: [
      "Free WiFi",
      "Air Conditioning",
      "Mini Bar",
      "Balcony",
      "Bathtub",
      "Breakfast Included",
    ],
    features: ["Private balcony", "Marble bathroom", "Garden-facing"],
    cancellationPolicy: "Free cancellation up to 72 hours before check-in.",
    breakfastIncluded: true,
    parkingIncluded: true,
    wifiIncluded: true,
    balcony: true,
    bathroomType: "Marble Ensuite Bath",
    location: "Dhaka",
    city: "Dhaka",
    country: "Bangladesh",
  }),

  createRoom({
    hotelId: 2,
    hotelName: "Aurelia Grand Hotel",
    roomName: "Superior City Room",
    roomType: "Superior Room",
    slug: "superior-city-room",
    description:
      "A refined superior room with upgraded furnishings, a spacious work desk, and sweeping views of the city skyline.",
    shortDescription: "Upgraded room with skyline views and a work desk.",
    price: 189,
    discountPrice: null,
    rating: 4.5,
    reviewCount: 76,
    availability: true,
    featured: false,
    roomNumber: "418",
    capacity: 2,
    adults: 2,
    children: 0,
    bedType: "1 King Bed",
    bedCount: 1,
    roomSize: "34 m²",
    floor: 4,
    view: "City View",
    mainImage:
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1200",
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=1200",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200",
    ],
    panoramaImage: "https://pannellum.org/images/alma.jpg",
    amenities: ["Free WiFi", "Air Conditioning", "Smart TV", "Work Desk", "City View"],
    features: ["Skyline view", "Extra workspace", "Sound-insulated windows"],
    cancellationPolicy: "Free cancellation up to 48 hours before check-in.",
    breakfastIncluded: false,
    parkingIncluded: false,
    wifiIncluded: true,
    location: "Sylhet",
    city: "Sylhet",
    country: "Bangladesh",
  }),

  createRoom({
    hotelId: 5,
    hotelName: "Ivory Tower Business Hotel",
    roomName: "Executive Business Room",
    roomType: "Executive Room",
    slug: "executive-business-room",
    description:
      "Designed for the modern traveler — a dedicated workspace, high-speed WiFi, and a calm, uncluttered space to recharge between meetings.",
    shortDescription: "Business-ready room with dedicated workspace.",
    price: 260,
    discountPrice: 219,
    rating: 4.6,
    reviewCount: 61,
    availability: true,
    featured: true,
    roomNumber: "515",
    capacity: 2,
    adults: 2,
    children: 0,
    bedType: "1 King Bed",
    bedCount: 1,
    roomSize: "36 m²",
    floor: 5,
    view: "City View",
    mainImage:
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200",
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=1200",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200",
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1200",
    ],
    panoramaImage: "https://pannellum.org/images/alma.jpg",
    amenities: ["Free WiFi", "Air Conditioning", "Work Desk", "Coffee Machine", "Safe Box"],
    features: ["Priority check-in", "Meeting room credit", "Airport transfer on request"],
    cancellationPolicy: "Free cancellation up to 24 hours before check-in.",
    breakfastIncluded: true,
    parkingIncluded: true,
    wifiIncluded: true,
    location: "Dhaka",
    city: "Dhaka",
    country: "Bangladesh",
  }),

  createRoom({
    hotelId: 3,
    hotelName: "Pinehill Family Resort",
    roomName: "Family Suite",
    roomType: "Family Room",
    slug: "family-suite",
    description:
      "A spacious family suite with two bedrooms, an elegant lounge, dining space, and beautiful garden-facing windows for memorable family vacations.",
    shortDescription: "Two-bedroom suite built for family stays.",
    price: 449,
    discountPrice: 399,
    rating: 4.7,
    reviewCount: 52,
    availability: false,
    featured: false,
    roomNumber: "108",
    capacity: 5,
    adults: 3,
    children: 2,
    bedType: "1 King + 2 Twin Beds",
    bedCount: 3,
    roomSize: "75 m²",
    floor: 1,
    view: "Garden View",
    mainImage:
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=1200",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200",
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1200",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200",
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=1200",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200",
    ],
    panoramaImage: "https://pannellum.org/images/alma.jpg",
    amenities: [
      "Free WiFi",
      "Air Conditioning",
      "Smart TV",
      "Breakfast Included",
      "Parking",
      "Wardrobe",
    ],
    features: ["Two connecting bedrooms", "Kids' welcome gift", "Family dining nook"],
    cancellationPolicy: "Free cancellation up to 72 hours before check-in.",
    breakfastIncluded: true,
    parkingIncluded: true,
    wifiIncluded: true,
    petsAllowed: true,
    location: "Cox's Bazar",
    city: "Cox's Bazar",
    country: "Bangladesh",
  }),

  createRoom({
    hotelId: 6,
    hotelName: "Coral Bay Beach Resort",
    roomName: "Ocean Breeze Junior Suite",
    roomType: "Junior Suite",
    slug: "ocean-breeze-junior-suite",
    description:
      "Wake up to breathtaking ocean views in this junior suite offering a private balcony, premium furnishings, and a rain shower bathroom.",
    shortDescription: "Ocean-view junior suite with a private balcony.",
    price: 269,
    discountPrice: null,
    rating: 4.9,
    reviewCount: 113,
    availability: true,
    featured: true,
    roomNumber: "622",
    capacity: 3,
    adults: 2,
    children: 1,
    bedType: "1 King Bed",
    bedCount: 1,
    roomSize: "48 m²",
    floor: 6,
    view: "Ocean View",
    mainImage:
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200",
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1200",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200",
      "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1200",
    ],
    panoramaImage: "https://pannellum.org/images/alma.jpg",
    amenities: [
      "Free WiFi",
      "Air Conditioning",
      "Balcony",
      "Ocean View",
      "Rain Shower",
      "Mini Bar",
    ],
    features: ["Private balcony", "Rain shower", "Steps from the beach"],
    cancellationPolicy: "Free cancellation up to 72 hours before check-in.",
    breakfastIncluded: true,
    parkingIncluded: true,
    wifiIncluded: true,
    balcony: true,
    bathroomType: "Rain Shower Ensuite",
    location: "Cox's Bazar",
    city: "Cox's Bazar",
    country: "Bangladesh",
  }),

  createRoom({
    hotelId: 1,
    hotelName: "The Regal Meridian",
    roomName: "Executive Suite",
    roomType: "Executive Suite",
    slug: "executive-suite",
    description:
      "An elegant executive suite with a spacious living area, panoramic skyline views, luxury bathroom, premium workspace, and exclusive lounge access.",
    shortDescription: "Spacious suite with skyline views and lounge access.",
    price: 389,
    discountPrice: 349,
    rating: 4.8,
    reviewCount: 67,
    availability: true,
    featured: true,
    roomNumber: "902",
    capacity: 3,
    adults: 2,
    children: 1,
    bedType: "1 King Bed + Sofa Bed",
    bedCount: 2,
    roomSize: "55 m²",
    floor: 9,
    view: "City View",
    mainImage:
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200",
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=1200",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200",
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1200",
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=1200",
    ],
    panoramaImage: "https://pannellum.org/images/alma.jpg",
    amenities: [
      "Free WiFi",
      "Air Conditioning",
      "Smart TV",
      "Mini Bar",
      "Bathtub",
      "Room Service",
    ],
    features: ["Executive lounge access", "Separate living area", "Panoramic skyline views"],
    cancellationPolicy: "Free cancellation up to 24 hours before check-in.",
    breakfastIncluded: true,
    parkingIncluded: true,
    wifiIncluded: true,
    bathroomType: "Marble Ensuite Bath",
    location: "Dhaka",
    city: "Dhaka",
    country: "Bangladesh",
  }),

  createRoom({
    hotelId: 1,
    hotelName: "The Regal Meridian",
    roomName: "Grand Presidential Suite",
    roomType: "Presidential Suite",
    slug: "grand-presidential-suite",
    description:
      "An entire floor transformed into a private sanctuary — panoramic skyline views, a private heated pool, dedicated butler, and interiors curated by an award-winning designer.",
    shortDescription: "The pinnacle of the collection — private pool and butler service.",
    price: 1299,
    discountPrice: null,
    rating: 5.0,
    reviewCount: 41,
    availability: true,
    featured: true,
    roomNumber: "PH1",
    capacity: 4,
    adults: 2,
    children: 2,
    bedType: "1 King Bed + Lounge",
    bedCount: 1,
    roomSize: "110 m²",
    floor: 20,
    view: "Panoramic City View",
    mainImage:
      "https://images.unsplash.com/photo-1631049552057-403cdb8f0658?w=1200&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1631049552057-403cdb8f0658?w=1200",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200",
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=1200",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200",
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1200",
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=1200",
    ],
    panoramaImage: "https://pannellum.org/images/alma.jpg",
    amenities: [
      "Free WiFi",
      "Air Conditioning",
      "Smart TV",
      "Mini Bar",
      "Bathtub",
      "Room Service",
      "Laundry",
    ],
    features: ["Private rooftop pool", "Dedicated butler", "In-suite spa"],
    cancellationPolicy: "Free cancellation up to 24 hours before check-in.",
    breakfastIncluded: true,
    parkingIncluded: true,
    wifiIncluded: true,
    balcony: true,
    bathroomType: "Marble Rain Shower + Soaking Tub",
    location: "Dhaka",
    city: "Dhaka",
    country: "Bangladesh",
  }),
];

// Distinct room types present in the data — used to build the type filter
// dropdown dynamically instead of a hardcoded list.
export const roomTypes = ["All", ...new Set(roomsData.map((r) => r.roomType))];

export function getRoomById(id) {
  return roomsData.find((r) => r.id === Number(id));
}

export function getFeaturedRoom(roomType) {
  return roomsData.find((r) => r.roomType === roomType);
}