export const hotelDetailsData = [
  {
    id: 1,
    name: "The Grand Aurum Palace",
    location: "Gulshan-1, Dhaka, Bangladesh",
    description:
      "The Grand Aurum Palace is Dhaka's most iconic five-star destination, offering an unparalleled fusion of classical architecture and contemporary luxury. Perched at the heart of the capital, every detail — from the hand-stitched silk drapes to the Italian marble lobbies — has been thoughtfully curated for the most discerning travellers. Our award-winning culinary team crafts menus inspired by global flavours, while the full-service spa delivers bespoke wellness journeys. Whether you're visiting for business or leisure, expect nothing short of extraordinary.",
    gallery: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=75",
    ],
    stars: 5,
    guestRating: 9.4,
    ratingLabel: "Exceptional",
    reviewCount: 2847,
    facilities: ["wifi", "pool", "spa", "gym", "parking", "restaurant"],
    rooms: [
      {
        id: 101,
        roomName: "Deluxe King Room",
        image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=600&q=75",
        bedType: "1 King Bed",
        guests: 2,
        size: "42 m²",
        price: 320,
        breakfast: true,
        freeCancellation: true,
      },
      {
        id: 102,
        roomName: "Premier Ocean Suite",
        image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=75",
        bedType: "1 King Bed + Sofa",
        guests: 3,
        size: "68 m²",
        price: 480,
        breakfast: true,
        freeCancellation: false,
      },
      {
        id: 103,
        roomName: "Classic Twin Room",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=75",
        bedType: "2 Twin Beds",
        guests: 2,
        size: "38 m²",
        price: 260,
        breakfast: false,
        freeCancellation: true,
      },
    ],
    policies: {
      checkIn: "3:00 PM",
      checkOut: "12:00 PM",
      cancellationPolicy:
        "Free cancellation up to 48 hours before check-in. Late cancellations or no-shows are charged 100% of the first night.",
    },
    reviews: [
      { user: "Sophia B.", rating: 10, comment: "Absolutely flawless — the staff went above and beyond. The infinity pool alone is worth the trip." },
      { user: "Luca M.", rating: 9, comment: "Stunning property in the heart of Dhaka. Breakfast was exceptional and the spa was deeply relaxing." },
      { user: "Aiko T.", rating: 9, comment: "Impeccable service, beautifully designed rooms. Will definitely return on my next visit." },
    ],
  },
  {
    id: 2,
    name: "Skyline Boutique Hotel",
    location: "Banani, Dhaka, Bangladesh",
    description:
      "Skyline Boutique Hotel is a chic urban retreat nestled in Dhaka's vibrant Banani district. Our contemporary design blends raw industrial elements with warm accents, creating spaces that feel both creative and comfortable. The rooftop terrace offers 360-degree views of the city skyline — perfect for sunset cocktails. With a curated selection of local and international artwork throughout, every corridor tells a story. Ideal for the modern traveller who values design, connectivity, and an authentic local experience.",
    gallery: [
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=75",
    ],
    stars: 4,
    guestRating: 8.7,
    ratingLabel: "Excellent",
    reviewCount: 1423,
    facilities: ["wifi", "gym", "parking"],
    rooms: [
      {
        id: 201,
        roomName: "Skyline Standard Room",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=75",
        bedType: "1 Queen Bed",
        guests: 2,
        size: "30 m²",
        price: 195,
        breakfast: false,
        freeCancellation: true,
      },
      {
        id: 202,
        roomName: "Rooftop Terrace Suite",
        image: "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?auto=format&fit=crop&w=600&q=75",
        bedType: "1 King Bed",
        guests: 2,
        size: "52 m²",
        price: 310,
        breakfast: true,
        freeCancellation: true,
      },
    ],
    policies: {
      checkIn: "2:00 PM",
      checkOut: "11:00 AM",
      cancellationPolicy:
        "Free cancellation up to 24 hours before check-in. After that, 50% of the total stay is charged.",
    },
    reviews: [
      { user: "Daniel K.", rating: 9, comment: "The rooftop view at night is unbeatable. Staff were super friendly and helpful." },
      { user: "Priya S.", rating: 8, comment: "Great location, stylish rooms. Would have loved a pool, but overall a great stay." },
    ],
  },
  {
    id: 3,
    name: "Azure Sea Resort & Spa",
    location: "Cox's Bazar, Bangladesh",
    description:
      "Azure Sea Resort & Spa stretches along the world's longest natural sea beach, offering a rare blend of coastal serenity and five-star luxury. Guests wake to the sound of waves and panoramic ocean views from private balconies. Our award-winning Aqua Spa draws from ancient Ayurvedic traditions, while the beachfront infinity pool creates a seamless visual merger with the sea beyond. Three speciality restaurants cater to every palate, from fresh seafood caught that morning to refined international cuisine.",
    gallery: [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=75",
    ],
    stars: 5,
    guestRating: 9.1,
    ratingLabel: "Exceptional",
    reviewCount: 3102,
    facilities: ["wifi", "pool", "spa", "restaurant", "gym"],
    rooms: [
      {
        id: 301,
        roomName: "Oceanfront Family Suite",
        image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=75",
        bedType: "1 King + 2 Twin Beds",
        guests: 4,
        size: "85 m²",
        price: 450,
        breakfast: true,
        freeCancellation: false,
      },
      {
        id: 302,
        roomName: "Beachview Deluxe Room",
        image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=600&q=75",
        bedType: "1 King Bed",
        guests: 2,
        size: "48 m²",
        price: 360,
        breakfast: true,
        freeCancellation: true,
      },
    ],
    policies: {
      checkIn: "3:00 PM",
      checkOut: "12:00 PM",
      cancellationPolicy:
        "Non-refundable rate. No cancellations accepted after booking is confirmed.",
    },
    reviews: [
      { user: "Ethan W.", rating: 10, comment: "The most beautiful resort I've ever stayed at. Waking up to the ocean every morning was magical." },
      { user: "Aiko T.", rating: 9, comment: "Spa was phenomenal. The Ayurvedic treatment left me completely rejuvenated." },
      { user: "Lucas M.", rating: 9, comment: "Family loved it. The kids' pool area and the beach access made it perfect for us." },
    ],
  },
  {
    id: 4,
    name: "Metropolitan Business Inn",
    location: "Motijheel, Dhaka, Bangladesh",
    description:
      "Metropolitan Business Inn is Dhaka's go-to address for the corporate traveller seeking smart comfort at an accessible price. Located in the commercial heart of Motijheel, our hotel places you steps from the city's key financial institutions and government offices. Rooms are compact yet thoughtfully designed with ergonomic workstations, blackout curtains, and ultra-fast WiFi. Our complimentary breakfast buffet ensures you start every day fuelled and focused.",
    gallery: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?auto=format&fit=crop&w=800&q=75",
    ],
    stars: 3,
    guestRating: 7.8,
    ratingLabel: "Good",
    reviewCount: 892,
    facilities: ["wifi", "parking"],
    rooms: [
      {
        id: 401,
        roomName: "Standard Single Room",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=75",
        bedType: "1 Single Bed",
        guests: 1,
        size: "22 m²",
        price: 75,
        breakfast: true,
        freeCancellation: true,
      },
      {
        id: 402,
        roomName: "Business Double Room",
        image: "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=600&q=75",
        bedType: "1 Double Bed",
        guests: 2,
        size: "30 m²",
        price: 95,
        breakfast: true,
        freeCancellation: true,
      },
    ],
    policies: {
      checkIn: "2:00 PM",
      checkOut: "12:00 PM",
      cancellationPolicy:
        "Free cancellation up to 48 hours before check-in. After that, 1 night's charge applies.",
    },
    reviews: [
      { user: "Ravi P.", rating: 8, comment: "Clean, well located, and the breakfast was surprisingly good. Great value." },
      { user: "Sarah L.", rating: 7, comment: "Functional and comfortable for a business trip. Nothing fancy but does the job well." },
    ],
  },
  {
    id: 5,
    name: "The Diplomat Residence",
    location: "Baridhara, Dhaka, Bangladesh",
    description:
      "The Diplomat Residence stands as Dhaka's most prestigious address, catering exclusively to heads of state, senior executives, and celebrities seeking absolute privacy and maximum sophistication. Every suite features bespoke furniture crafted by local artisans, a private dining area, and a dedicated butler available 24 hours. The wine cellar, curated by a master sommelier, houses over 800 labels. Security, discretion, and flawless service define every moment of your stay.",
    gallery: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?auto=format&fit=crop&w=800&q=75",
    ],
    stars: 5,
    guestRating: 9.6,
    ratingLabel: "Exceptional",
    reviewCount: 4201,
    facilities: ["wifi", "pool", "spa", "gym", "restaurant", "parking"],
    rooms: [
      {
        id: 501,
        roomName: "Presidential Suite",
        image: "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?auto=format&fit=crop&w=600&q=75",
        bedType: "1 Super King Bed",
        guests: 2,
        size: "180 m²",
        price: 680,
        breakfast: true,
        freeCancellation: true,
      },
      {
        id: 502,
        roomName: "Ambassador Suite",
        image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=600&q=75",
        bedType: "1 King Bed",
        guests: 2,
        size: "110 m²",
        price: 520,
        breakfast: true,
        freeCancellation: true,
      },
    ],
    policies: {
      checkIn: "4:00 PM",
      checkOut: "1:00 PM",
      cancellationPolicy:
        "Free cancellation up to 72 hours before check-in. Within 72 hours, 100% of total stay is charged.",
    },
    reviews: [
      { user: "James A.", rating: 10, comment: "The finest hotel experience of my life. The butler service was seamlessly anticipatory." },
      { user: "Yuki T.", rating: 10, comment: "Absolute perfection. Every detail attended to without being asked. The definition of luxury." },
      { user: "Olivia R.", rating: 9, comment: "Breathtaking property. The wine cellar dinner was the highlight of our trip to Dhaka." },
    ],
  },
  {
    id: 6,
    name: "Garden View Suites",
    location: "Dhanmondi, Dhaka, Bangladesh",
    description:
      "Garden View Suites is a serene haven tucked into the leafy residential calm of Dhanmondi. Designed around a lush central courtyard garden, our suites open directly onto private verandahs overlooking manicured greenery — a rare luxury in urban Dhaka. We cater to families, long-stay guests, and those who prefer space over spectacle. A heated outdoor pool, a warm restaurant serving Bangladeshi and international comfort food, and our attentive family-first service make Garden View Suites a home away from home.",
    gallery: [
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=75",
    ],
    stars: 4,
    guestRating: 8.2,
    ratingLabel: "Very Good",
    reviewCount: 1105,
    facilities: ["wifi", "pool", "parking", "restaurant"],
    rooms: [
      {
        id: 601,
        roomName: "Garden Deluxe Suite",
        image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=75",
        bedType: "1 King Bed",
        guests: 2,
        size: "55 m²",
        price: 155,
        breakfast: true,
        freeCancellation: true,
      },
      {
        id: 602,
        roomName: "Family Garden Suite",
        image: "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=600&q=75",
        bedType: "1 King + 1 Bunk Bed",
        guests: 4,
        size: "78 m²",
        price: 210,
        breakfast: true,
        freeCancellation: true,
      },
    ],
    policies: {
      checkIn: "2:00 PM",
      checkOut: "12:00 PM",
      cancellationPolicy:
        "Free cancellation up to 48 hours before check-in. Partial charge applies for late cancellations.",
    },
    reviews: [
      { user: "Mei L.", rating: 8, comment: "Such a peaceful property! The garden is beautiful and the kids loved the pool." },
      { user: "Carlos R.", rating: 8, comment: "Great for families. Lots of space, friendly staff and the food is home-cooked quality." },
    ],
  },
  {
    id: 7,
    name: "Harbour Lights Hotel",
    location: "Old Dhaka, Bangladesh",
    description:
      "Harbour Lights Hotel occupies a lovingly restored colonial-era building on the banks of the Buriganga River. The property marries heritage architecture with modern comforts — original wooden beams and terracotta tile floors coexist with pillow-top mattresses and rain showers. Our rooftop restaurant is celebrated for its evening river views and fresh water-to-table seafood menu. Walking tours of Old Dhaka's Mughal-era mosques, spice markets, and river ghats depart from our front door.",
    gallery: [
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=75",
    ],
    stars: 4,
    guestRating: 8.5,
    ratingLabel: "Excellent",
    reviewCount: 978,
    facilities: ["wifi", "gym", "restaurant"],
    rooms: [
      {
        id: 701,
        roomName: "Heritage River View Room",
        image: "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=600&q=75",
        bedType: "1 Queen Bed",
        guests: 2,
        size: "35 m²",
        price: 210,
        breakfast: false,
        freeCancellation: false,
      },
      {
        id: 702,
        roomName: "Colonial Courtyard Suite",
        image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=75",
        bedType: "1 King Bed",
        guests: 2,
        size: "50 m²",
        price: 290,
        breakfast: false,
        freeCancellation: false,
      },
    ],
    policies: {
      checkIn: "3:00 PM",
      checkOut: "11:00 AM",
      cancellationPolicy:
        "Non-refundable. Modifications are subject to availability and may incur fees.",
    },
    reviews: [
      { user: "Tom B.", rating: 9, comment: "So much character! The history of this building adds so much to the experience." },
      { user: "Fatima A.", rating: 8, comment: "The rooftop dinner over the river was unforgettable. Unique hotel in a unique setting." },
    ],
  },
  {
    id: 8,
    name: "Prestige Penthouse Hotel",
    location: "Uttara, Dhaka, Bangladesh",
    description:
      "Prestige Penthouse Hotel redefines the concept of sky-high living in Dhaka. Our 42-floor tower hosts only 60 exclusive suites, each spanning an entire floor segment with unobstructed panoramic views of the city. The crown jewel is the 40th-floor infinity pool that appears to float among the clouds. Our Michelin-inspired restaurant, Altitude, serves a 7-course tasting menu that changes monthly. For families, the supervised kids' adventure zone and family spa treatment rooms offer experiences as lavish for the young as the adults.",
    gallery: [
      "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=75",
    ],
    stars: 5,
    guestRating: 9.3,
    ratingLabel: "Exceptional",
    reviewCount: 2210,
    facilities: ["wifi", "pool", "spa", "gym", "restaurant", "parking"],
    rooms: [
      {
        id: 801,
        roomName: "Sky Penthouse Suite",
        image: "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?auto=format&fit=crop&w=600&q=75",
        bedType: "1 Super King Bed",
        guests: 2,
        size: "150 m²",
        price: 520,
        breakfast: true,
        freeCancellation: true,
      },
      {
        id: 802,
        roomName: "Family Panorama Suite",
        image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=75",
        bedType: "1 King + 2 Twin Beds",
        guests: 4,
        size: "200 m²",
        price: 680,
        breakfast: true,
        freeCancellation: true,
      },
      {
        id: 803,
        roomName: "Cloud View Double",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=75",
        bedType: "1 King Bed",
        guests: 2,
        size: "65 m²",
        price: 380,
        breakfast: false,
        freeCancellation: true,
      },
    ],
    policies: {
      checkIn: "3:00 PM",
      checkOut: "12:00 PM",
      cancellationPolicy:
        "Free cancellation up to 72 hours before check-in. Within 72 hours, 100% of stay is charged.",
    },
    reviews: [
      { user: "Yuki T.", rating: 10, comment: "The infinity pool on the 40th floor is the most dramatic thing I've ever seen. Absolutely stunning." },
      { user: "Marco V.", rating: 9, comment: "Altitude restaurant's tasting menu was a culinary journey. The views made it even more special." },
      { user: "Hannah C.", rating: 9, comment: "Perfect for our family trip. The kids' zone kept the little ones happy while we relaxed at the spa." },
    ],
  },
];

export default hotelDetailsData;