export const roomSelectionData = [
  {
    id: 1,
    hotelId: 1,
    name: "Deluxe King Room",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=75",
    gallery: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=75",
    ],
    description: "A spacious room with floor-to-ceiling windows overlooking the cityscape. Features premium Italian marble bathroom, walk-in wardrobe, and a dedicated work desk.",
    roomSize: 42,
    maxGuests: 2,
    bedType: "1 King Bed",
    price: 320,
    originalPrice: 420,
    breakfast: true,
    freeCancellation: true,
    availableRooms: 3,
    badge: "Best Value",
    badgeColor: "#0369a1",
    facilities: ["wifi", "ac", "breakfast", "freeCancellation", "tv", "bathroom", "minibar", "coffee"],
  },
  {
    id: 2,
    hotelId: 1,
    name: "Premier Ocean Suite",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=75",
    gallery: [
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?auto=format&fit=crop&w=800&q=75",
    ],
    description: "An expansive suite with panoramic ocean views from a private wraparound terrace. Includes a separate lounge area, soaking tub, and butler service.",
    roomSize: 68,
    maxGuests: 3,
    bedType: "1 King Bed + Sofa",
    price: 480,
    originalPrice: 600,
    breakfast: true,
    freeCancellation: false,
    availableRooms: 2,
    badge: "High Demand",
    badgeColor: "#b45309",
    facilities: ["wifi", "ac", "breakfast", "tv", "bathroom", "minibar", "coffee"],
  },
  {
    id: 3,
    hotelId: 1,
    name: "Classic Twin Room",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=75",
    gallery: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=75",
    ],
    description: "A well-appointed twin room ideal for colleagues or friends. Features two plush single beds, a compact work area, and a sleek ensuite bathroom.",
    roomSize: 38,
    maxGuests: 2,
    bedType: "2 Single Beds",
    price: 260,
    originalPrice: 320,
    breakfast: false,
    freeCancellation: true,
    availableRooms: 5,
    badge: null,
    badgeColor: null,
    facilities: ["wifi", "ac", "freeCancellation", "tv", "bathroom", "coffee"],
  },
  {
    id: 4,
    hotelId: 1,
    name: "Presidential Suite",
    image: "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?auto=format&fit=crop&w=800&q=75",
    gallery: [
      "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?auto=format&fit=crop&w=800&q=75",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=75",
    ],
    description: "The pinnacle of luxury — a full-floor private suite with wraparound terrace, in-suite spa, chef's kitchen, private dining room, and dedicated butler.",
    roomSize: 180,
    maxGuests: 4,
    bedType: "1 Super King Bed",
    price: 1200,
    originalPrice: 1500,
    breakfast: true,
    freeCancellation: true,
    availableRooms: 1,
    badge: "Only 1 left",
    badgeColor: "#dc2626",
    facilities: ["wifi", "ac", "breakfast", "freeCancellation", "tv", "bathroom", "minibar", "coffee"],
  },
  {
    id: 5,
    hotelId: 2,
    name: "Skyline Standard Room",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=75",
    gallery: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=75"],
    description: "A stylish room blending industrial chic with warm textiles. Perfect for solo travellers or couples seeking urban comfort.",
    roomSize: 30,
    maxGuests: 2,
    bedType: "1 Queen Bed",
    price: 195,
    originalPrice: 240,
    breakfast: false,
    freeCancellation: true,
    availableRooms: 4,
    badge: "Best Value",
    badgeColor: "#0369a1",
    facilities: ["wifi", "ac", "freeCancellation", "tv", "bathroom"],
  },
  {
    id: 6,
    hotelId: 2,
    name: "Rooftop Terrace Suite",
    image: "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?auto=format&fit=crop&w=800&q=75",
    gallery: ["https://images.unsplash.com/photo-1560347876-aeef00ee58a1?auto=format&fit=crop&w=800&q=75"],
    description: "Access a private rooftop terrace with sweeping 360° city views. This suite blends open-plan living with curated art pieces throughout.",
    roomSize: 52,
    maxGuests: 2,
    bedType: "1 King Bed",
    price: 310,
    originalPrice: 380,
    breakfast: true,
    freeCancellation: true,
    availableRooms: 2,
    badge: "High Demand",
    badgeColor: "#b45309",
    facilities: ["wifi", "ac", "breakfast", "freeCancellation", "tv", "bathroom", "minibar", "coffee"],
  },
];

export const hotelSummaryData = [
  {
    id: 1,
    name: "The Grand Aurum Palace",
    location: "Gulshan-1, Dhaka, Bangladesh",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=75",
    stars: 5,
    guestRating: 9.4,
    ratingLabel: "Exceptional",
    reviewCount: 2847,
  },
  {
    id: 2,
    name: "Skyline Boutique Hotel",
    location: "Banani, Dhaka, Bangladesh",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=75",
    stars: 4,
    guestRating: 8.7,
    ratingLabel: "Excellent",
    reviewCount: 1423,
  },
];